sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t alexnick/docker-react .

script:
  - docker run alexnick/docker-react yarn vitest

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: "Docker-env"
  bucket: "docker-react-bucket"
  bucket_path: "docker-react"
  on:
    branch: main
